# Kratos configuration for e2e testing (all services running inside Docker).
# See the full config at https://www.ory.sh/docs/kratos/reference/configuration
version = "v25.4.0"

dsn = "postgres://postgres@secutils_db:5432/secutils?sslmode=disable&max_conns=20&max_idle_conns=4&search_path=kratos,public"

[serve]
public.base_url = "http://localhost:7171"
admin.base_url = "http://kratos:4433"

[log]
level = "info"
format = "text"
leak_sensitive_values = true

[identity]
default_schema_id = "user"
schemas = [{ id = "user", url = "file:///etc/config/kratos/user_identity.schema.json" }]

[session]
cookie = { name = "id" }

[selfservice]
default_browser_return_url = "http://localhost:7171/"
allowed_return_urls = ["http://localhost:7171"]

[selfservice.methods]
code = { enabled = true, config = { lifespan = "15m" } }
password = { enabled = true }
webauthn = { enabled = true, config = { passwordless = true, rp = { display_name = "Secutils.dev", id = "localhost", origin = "http://localhost:7171" } } }

[selfservice.flows]
recovery = { enabled = true, lifespan = "15m", use = "code", notify_unknown_recipients = false, after = { hooks = [{  hook = "revoke_active_sessions" }] } }
settings = { privileged_session_max_age = "15m" }
verification = { enabled = true }

[selfservice.flows.registration.after.password]
hooks = [
    { hook = "web_hook", config = { method = "POST", url = "http://secutils_api:7070/api/users/signup", response = { ignore = false, parse = false }, body = "base64://ZnVuY3Rpb24oY3R4KSB7IGlkZW50aXR5OiBjdHguaWRlbnRpdHkgfQ==", auth = { type = "api_key", config.name = "Authorization", config.in = "header" } } },
    { hook = "session" }
]

[selfservice.flows.registration.after.webauthn]
hooks = [
    { hook = "web_hook", config = { method = "POST", url = "http://secutils_api:7070/api/users/signup", response = { ignore = false, parse = false }, body = "base64://ZnVuY3Rpb24oY3R4KSB7IGlkZW50aXR5OiBjdHguaWRlbnRpdHkgfQ==", auth = { type = "api_key", config.name = "Authorization", config.in = "header" } } },
    { hook = "session" }
]

[courier]
delivery_strategy = "http"
http = { request_config = { url = "http://secutils_api:7070/api/users/email", method = "POST", body = "base64://ZnVuY3Rpb24oY3R4KSB7CiAgcmVjaXBpZW50OiBjdHgucmVjaXBpZW50LAogIHRlbXBsYXRlX3R5cGU6IGN0eC50ZW1wbGF0ZV90eXBlLAogIGlkZW50aXR5OiBjdHgudGVtcGxhdGVfZGF0YS5pZGVudGl0eSwKICByZWNvdmVyeV9jb2RlOiBpZiAidGVtcGxhdGVfZGF0YSIgaW4gY3R4ICYmICJyZWNvdmVyeV9jb2RlIiBpbiBjdHgudGVtcGxhdGVfZGF0YSB0aGVuIGN0eC50ZW1wbGF0ZV9kYXRhLnJlY292ZXJ5X2NvZGUgZWxzZSBudWxsLAogIHJlY292ZXJ5X3VybDogaWYgInRlbXBsYXRlX2RhdGEiIGluIGN0eCAmJiAicmVjb3ZlcnlfdXJsIiBpbiBjdHgudGVtcGxhdGVfZGF0YSB0aGVuIGN0eC50ZW1wbGF0ZV9kYXRhLnJlY292ZXJ5X3VybCBlbHNlIG51bGwsCiAgdmVyaWZpY2F0aW9uX3VybDogaWYgInRlbXBsYXRlX2RhdGEiIGluIGN0eCAmJiAidmVyaWZpY2F0aW9uX3VybCIgaW4gY3R4LnRlbXBsYXRlX2RhdGEgdGhlbiBjdHgudGVtcGxhdGVfZGF0YS52ZXJpZmljYXRpb25fdXJsIGVsc2UgbnVsbCwKICB2ZXJpZmljYXRpb25fY29kZTogaWYgInRlbXBsYXRlX2RhdGEiIGluIGN0eCAmJiAidmVyaWZpY2F0aW9uX2NvZGUiIGluIGN0eC50ZW1wbGF0ZV9kYXRhIHRoZW4gY3R4LnRlbXBsYXRlX2RhdGEudmVyaWZpY2F0aW9uX2NvZGUgZWxzZSBudWxsCn0=", headers = { "Content-Type" = "application/json" }, auth = { type = "api_key", config.name = "Authorization", config.in = "header" } } }
